from __future__ import annotations

from typing import Any, Dict, Optional
from pydantic import BaseModel, ConfigDict, Field


class ProblemDetails(BaseModel):
    """RFC 7807 compliant problem details schema."""

    type: str = Field(
        ...,
        description="A URI reference that identifies the problem type.",
        examples=["https://api.platform.internal/errors/illegal-state-transition"],
    )
    title: str = Field(
        ...,
        description="A short, human-readable summary of the problem type.",
        examples=["Illegal State Transition"],
    )
    status: int = Field(
        ...,
        description="The HTTP status code generated by the origin server.",
        examples=[409],
    )
    detail: str = Field(
        ...,
        description="A human-readable explanation specific to this occurrence of the problem.",
        examples=["Cannot transition subscription from CANCELED to ACTIVE."],
    )
    instance: Optional[str] = Field(
        None,
        description="A URI reference that identifies the specific occurrence of the problem.",
        examples=["/v1/subscriptions/sub_123/charge"],
    )

    model_config = ConfigDict(extra="allow")
